apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poiblr-poi-backend-app-dev
  annotations:
    argocd/app-name: poiblr-poi-backend-app-dev
    backstage.io/kubernetes-id: poiblr-poi-backend-app
    backstage.io/kubernetes-namespace: poiblr
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-connect/poiblr-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-8lznb.l07n.p1.openshiftapps.com/dev-pipelines/ns/poiblr/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-8lznb.l07n.p1.openshiftapps.com/k8s/ns/poiblr/deployments/poiblr-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-8lznb.l07n.p1.openshiftapps.com/#https://github.com/rhdh-connect/poiblr-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ramkrsna"
  system: workshop-system-poiblr
  providesApis:
    - backend-api-poiblr
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-poiblr
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ramkrsna"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-poiblr
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://poiblr-poi-backend-app-poiblr.apps.rosa-8lznb.l07n.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-connect/poiblr-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/ramkrsna"
  system: workshop-system-poiblr
  definition:
    $text: https://github.com/rhdh-connect/poiblr-backend/tree/main/src/main/resources/META-INF/openapi.yaml
